[".hammerspoon/fennel.lua"]
type = "file"
url = "https://fennel-lang.org/downloads/fennel-1.2.0.tar.gz"
refreshPeriod = "168h"
[".hammerspoon/fennel.lua".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fennel-1.2.0/fennel.lua"]

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"
