[".hammerspoon/fennel.lua"]
type = "file"
url = "https://fennel-lang.org/downloads/fennel-1.2.0.tar.gz"
refreshPeriod = "168h"
[".hammerspoon/fennel.lua".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fennel-1.2.0/fennel.lua"]

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"

[".config/fish/functions/fisher.fish"]
type = "file"
url = "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"
refreshPeriod = "168h"

[".config/fish/completions/fisher.fish"]
type = "file"
url = "https://raw.githubusercontent.com/jorgebucaran/fisher/main/completions/fisher.fish"
refreshPeriod = "168h"

[".config/kitty/kitty.falcon.conf"]
type = "file"
url = "https://raw.githubusercontent.com/fenetikm/falcon/master/kitty/kitty.falcon.conf"
refreshPeriod = "168h"
