" install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $HOME/.vimrc
endif

" plugins
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'              " a sensible vimrc default

Plug 'benhinchley/ghost'               " custom colorscheme
Plug 'vim-airline/vim-airline'         " statusbar

Plug 'moll/vim-bbye'                   " delete buffers without closing windows

Plug 'ervandew/supertab'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'

Plug 'Raimondi/delimitMate'            " auto closing of quotes, parens, brackets, etc.
Plug 'scrooloose/nerdcommenter'        " commenting helpers
Plug 'airblade/vim-gitgutter'          " show gitt diff in the sign column
Plug 'editorconfig/editorconfig-vim'   " editorconfig plugin
Plug 'bronson/vim-trailing-whitespace' " highlight trailing whitespace

Plug 'w0rp/ale'                        " async linter runner
Plug 'majutsushi/tagbar', { 'for': ['go', 'rust'] }

Plug 'fatih/vim-go', { 'for': 'go' } " go dev
Plug 'leafgarland/typescript-vim'    " typescript syntax
call plug#end()

" show relative numbers when in normal mode
set relativenumber
augroup toggle_relative_number
    autocmd!
    autocmd InsertEnter * :setlocal norelativenumber
    autocmd InsertLeave * :setlocal relativenumber
augroup END

" clipboard
set clipboard=unnamed " automatically yank into the system clipboard

" set colorscheme
set background=dark
colorscheme ghost

" airline theme
let g:airline_theme='ghost'
let g:airline_powerline_fonts=0

" column markers
:call matchadd('ColorColumn', '\%101v', 100)

" nercommenter
let g:NERDSpaceDelims = 1 " Add spaces after comment delimiters

" KEY REMAPS
" disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" leader
let mapleader = " " " set leader to spacebar

" make semicolon colon and vice versa
nnoremap ; :
nnoremap : ;

" bye bye buffer
nnoremap <Leader>q :Bdelete<CR>

" Nobody ever uses "Ex" mode, and it's annoying to leave
noremap Q <nop>

" get rid of the mouse
noremap <ScrollWheelUp>      <nop>
noremap <S-ScrollWheelUp>    <nop>
noremap <C-ScrollWheelUp>    <nop>
noremap <ScrollWheelDown>    <nop>
noremap <S-ScrollWheelDown>  <nop>
noremap <C-ScrollWheelDown>  <nop>
noremap <ScrollWheelLeft>    <nop>
noremap <S-ScrollWheelLeft>  <nop>
noremap <C-ScrollWheelLeft>  <nop>
noremap <ScrollWheelRight>   <nop>
noremap <S-ScrollWheelRight> <nop>
noremap <C-ScrollWheelRight> <nop>

" make
noremap <F9> :make<CR>

" tagbar
noremap <F8> :TagbarToggle<CR>

" make pane movement simpler
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" go
autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
let g:go_fmt_command = "goimports"

" ale
let g:ale_open_list = 0
let g:airline#extensions#ale#enabled = 1

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

" fzf
nnoremap <leader>ff :Files<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>fl :Lines<CR>

let g:fzf_colors = {
      \ 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Statement'],
      \ 'info':    ['fg', 'PreProc'],
      \ 'border':  ['fg', 'Ignore'],
      \ 'prompt':  ['fg', 'Conditional'],
      \ 'pointer': ['fg', 'Exception'],
      \ 'marker':  ['fg', 'Keyword'],
      \ 'spinner': ['fg', 'Label'],
      \ 'header':  ['fg', 'Comment'] }

