#!/usr/bin/env bash

(command -v brew > /dev/null) || {
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

brew tap caskroom/cask
brew install git git-lfs hub direnv fzf fd bash-completion coreutils shellcheck vim protobuf bat jq ripgrep
brew cask install font-fira-code
