[user]
email = "7188324+benhinchley@users.noreply.github.com"
name = "Benjamin Hinchley"

# TODO: Figure out why this doesn't work.
# [ui]
# diff-editor = "idea"
#
# [merge-tools.idea]
# program="/Users/benjaminhinchley/.local/bin/idea"
# diff-args = ["diff", "$left", "$right"]
# edit-args = ["diff", "$left", "$right"]
# merge-args = ["merge", "$left", "$right", "$base", "$output"]
