#!/usr/bin/env bash

# bash completion
if [ -f /usr/local/etc/bash_completion ]; then source /usr/local/etc/bash_completion; fi

# PS1
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export PS1="\\A \\W\$(__git_ps1 ':[%s]')\\n$ "

# aliases
alias l="ls -lF"
alias la="ls -laF"
alias ls="command ls"
alias mkdir="mkdir -p"
alias ping="ping -c 10"
alias cat="bat"
alias git="hub"
alias g="git"
alias m="make"
alias k="kubectl"
alias kubectl="command kubectl"
alias r="review"

# functions
csv() { sed -e 's/,,/, ,/g' | column -s, -t | less -\#5 -N -S ;}

goinstall() {
	if [[ $# -ne 1 ]]; then
		echo "version number needed"
		return 1
	fi

	local VERSION="$1"

	if [ ! -f "$HOME/Downloads/go$VERSION.tar.gz" ]; then
		echo "downloading go $VERSION"
		curl -o "$HOME/Downloads/go$VERSION.tar.gz" -sL \
			"https://dl.google.com/go/go$VERSION.darwin-amd64.tar.gz"
	fi

	echo "removing go $(go version | sed 's/go version go//')"
	sudo rm -rf /usr/local/go

	echo "installing go $VERSION darwin/amd64"
	sudo tar -C /usr/local -xzf "$HOME/Downloads/go$VERSION.tar.gz"
}

# Append to history file
shopt -s histappend
# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoreboth;
# Make some commands not show up in history
export HISTIGNORE=" *:ls:cd:cd -:pwd:exit:date:* --help:* -h:pony:pony add *:pony update *:pony save *:pony ls:pony ls *:clear:&";
export PROMPT_COMMAND="history -a"

# GPG
GPG_TTY=$(tty)
export GPG_TTY

# gcloud
if [ -f "${HOME}/google-cloud-sdk/path.bash.inc" ]; then source "${HOME}/google-cloud-sdk/path.bash.inc"; fi
if [ -f "${HOME}/google-cloud-sdk/completion.bash.inc" ]; then source "${HOME}/google-cloud-sdk/completion.bash.inc"; fi
export CLOUDSDK_PYTHON=$(command -v python2)
if command -v dev_appserver.py > /dev/null; then
    alias dev_appserver="dev_appserver.py --support_datastore_emulator=True"
fi

# fzf
[ -f "$HOME/.fzf.bash" ] && source "$HOME/.fzf.bash"
export FZF_DEFAULT_OPTS="--no-mouse --ansi --cycle --reverse --no-height \
	--color=info:243,prompt:243,pointer:46,spinner:201 \
	--color=fg:7,bg:233,hl:190,hl+:190"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'head -100 {}'"

# python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# go
export GOPATH="$HOME/.go/thirdparty:$HOME/.go/projects"
export PATH="$HOME/.go/thirdparty/bin:$HOME/.go/projects/bin:$PATH:/usr/local/go/bin"
export CDPATH=${CDPATH}:$HOME/.go/projects/src/github.com:$HOME/.go/projects/src

# repositories
export CDPATH=${CDPATH}:$HOME/.code/github.com

# coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# direnv
eval "$(direnv hook bash)"

export PATH=/Users/ben/.local/bin:$PATH

# Volta
export VOLTA_HOME="$HOME/.volta"
[ -s "$VOLTA_HOME/load.sh" ] && . "$VOLTA_HOME/load.sh"
export PATH="$VOLTA_HOME/bin:$PATH"
